### PR TITLE
New tab for show internal transactions history for a given address

### LINKED ISSUE #226: Implement the same internal tx tab that etherscan has on the account page.
Would also be nice to have the Internal tx tab that etherscan has on the account page.

_Originally posted by @tomtomcrypto in https://github.com/telosnetwork/teloscan/issues/93#issuecomment-1304788296_

# Description

Currently we cannot see some account transactions like TLOS receipts.
We need to add a tab to the account page that shows internal transactions related to the account, like etherscan does:

image

# Task

- [ ] Add new tab
- [ ] Get relevant internal transactions
- [ ] Parse internal transactions

# Acceptance

The account page has a new tab "Internal tx" that shows a list of all related internal transaction to the account.

### PR DESCRIPTION
**Pull request by Viterbo**
# Fixes #226

## Description
This PR adds a new tab on the account page to show the same transaction pagination but focused on showing the internal transactions for each parent transaction.

As default behavior, the internal transactions data is visible for all transactions but the user can close and reopen the section for each transaction individually using a switcher on the right of the transaction header.

## Test scenarios
- Normal navigation
   - Go to [this address account page](https://deploy-preview-346--dev-mainnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a)
   - Press the Internal Transactions Tab
   - You should see the first page of transactions (currently all of them have zero int-trxs)
   - change the page until you see a transaction with some internal transactions
   - close ad reopen the content section of any transaction (using the switcher on the right of the header)
- Pagination by url: access directly
   - Go directly to the [second page](https://deploy-preview-346--dev-mainnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a?page=2,20#int_transactions) with 20 rows per page
   - You should be on the second page and see 20 rows
- Pagination by url: back button
   - Go to the internal [transaction tab](https://deploy-preview-346--dev-mainnet-teloscan.netlify.app/address/0xa30b5e3c8Fee56C135Aecb733cd708cC31A5657a#int_transactions)
   - Navigate to several pages forward
   - Then navigate away from the current table
   - press the back button from your browser
   - You should see the last pagination in the internal transaction tab

# Screenshots

image

image

## Checklist:

-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have cleaned up the code in the areas my change touches
-   [x] My changes generate no new warnings
-   [x] Any dependent changes have been merged and published in downstream modules
-   [x] I have checked my code and corrected any misspellings
-   [x] I have removed any unnecessary console messages
-   [x] I have included all english text to the translation file

### CODE REVIEW

**Review by EJSG — CHANGES_REQUESTED** [review]
looks really good overall, nice work! i think this seems to accomplish the goal of the ticket. lets see if @tomtomcrypto agrees as he made the original ticket.

the only issue i found is that if you go a few pages in the table, then navigate to somewhere else like the Health page, if you try to navigate back in history it goes to a URL like `https://deploy-preview-346--dev-mainnet-teloscan.netlify.app/?page=2&pagesize=10` (which is the home page with pagination). I think the issue _might_ be at line 138 in the new component because it uses `pushState` instead of `replaceState`.

**Comment by Viterbo** [comment]
I changed the strategy from a homemade solution using history.pushState to a more easy and elegant solution using $router (which is intended for these cases).

```typescript
    async onPaginationChange(props) {
        const { page, rowsPerPage } = props.pagination;
        this.$router.push({
            hash: window.location.hash,
            query: {
                ...this.$route.query,
                page: `${page},${rowsPerPage}`,
            },
        });
    },
```

```typescript
watch: {
    '$route.query.page': {
        handler(_pag) {
            let pag = _pag;
            let page = 1;
            let size = this.pagination.rowsPerPage;

            // we also allow to pass a single number as the page number
            if (typeof pag === 'number') {
                page = pag;
            } else if (typeof pag === 'string') {
                // we also allow to pass a string of two numbers: [page, rowsPerPage]
                const [p, s] = pag.split(',');
                page = p;
                size = s;
            }

            this.setPagination(page, size);
        },
        immediate: true,
    },
},
```

I'm going to create a new issue to implement this same solution on the TransactionTable

**Review by EJSG — APPROVED** [review]
awesome :rocket:

**Review by EJSG — CHANGES_REQUESTED** [review]
sorry haha, found one issue, see my comment here
https://github.com/telosnetwork/teloscan/pull/351#pullrequestreview-1281639813

**Review by EJSG — APPROVED** [review]
:clap:

**Review by donnyquixotic — APPROVED** [review]

**Pull request merged**
